In [1]:
import pandas as pd
import numpy as np

In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder

In [5]:
from sklearn.compose import ColumnTransformer

In [7]:
from sklearn.pipeline import Pipeline

In [9]:
from sklearn.decomposition import PCA

In [11]:
from sklearn.preprocessing import FunctionTransformer

In [13]:
from sklearn.model_selection import train_test_split

In [15]:
data = pd.read_csv(r'C:\Users\anaah\OneDrive\Desktop\pcadata.csv')


In [17]:
X = data.drop('outcome', axis=1)
y = data['outcome']

In [19]:
print(data.head())

          A         B         c         D         E  outcome
0 -1.303652 -0.309452  0.507558  0.047561 -0.058751        0
1 -1.345033 -0.190036  0.232680  0.089590 -0.127793        0
2  2.100616 -0.255979 -0.588517  0.290465  0.090128        1
3  1.632936 -0.509005 -0.047196  0.209240  0.124278        0
4  0.918260 -0.809181  0.636449  0.105736 -0.009965        1


In [21]:
print(data.head())

          A         B         c         D         E  outcome
0 -1.303652 -0.309452  0.507558  0.047561 -0.058751        0
1 -1.345033 -0.190036  0.232680  0.089590 -0.127793        0
2  2.100616 -0.255979 -0.588517  0.290465  0.090128        1
3  1.632936 -0.509005 -0.047196  0.209240  0.124278        0
4  0.918260 -0.809181  0.636449  0.105736 -0.009965        1


In [23]:
print(data.head())

          A         B         c         D         E  outcome
0 -1.303652 -0.309452  0.507558  0.047561 -0.058751        0
1 -1.345033 -0.190036  0.232680  0.089590 -0.127793        0
2  2.100616 -0.255979 -0.588517  0.290465  0.090128        1
3  1.632936 -0.509005 -0.047196  0.209240  0.124278        0
4  0.918260 -0.809181  0.636449  0.105736 -0.009965        1


In [26]:
print(data.columns)

Index(['A', 'B', 'c', 'D', 'E', 'outcome'], dtype='object')


In [28]:
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns

In [30]:
categorical_features = X.select_dtypes(include=['object']).columns

In [32]:
numerical_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),('pca', PCA(n_components=5))
])

In [34]:
categorical_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),('onehot', OneHotEncoder(handle_unknown='ignore'))
])

In [36]:
preprocessor = ColumnTransformer(
    transformers=[('num', numerical_pipeline, numerical_features),('cat', categorical_pipeline, categorical_features)
    ])

In [38]:
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
])

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('pca',
                                                                   PCA(n_components=5))]),
                                                  Index(['A', 'B', 'c', 'D', 'E'], dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index([], dtype='object'))]))])

In [44]:
score = pipeline.score(X_test, y_test)
print(f'Model accuracy: {score:.2f}')

AttributeError: This 'Pipeline' has no attribute 'score'

In [46]:
from sklearn.metrics import accuracy_score
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy score: {accuracy:.2f}')

AttributeError: This 'Pipeline' has no attribute 'predict'

In [48]:
from sklearn.model_selection import cross_val_score
cv_scores = cross_val_score(pipeline, X, y, cv=5)
print(f'Cross-validated scores: {cv_scores}')
print(f'Mean cross-validated score: {cv_scores.mean():.2f}')


TypeError: If no scoring is specified, the estimator passed should have a 'score' method. The estimator Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('pca',
                                                                   PCA(n_components=5))]),
                                                  Index(['A', 'B', 'c', 'D', 'E'], dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index([], dtype='object'))]))]) does not.

In [50]:
X_train_transformed = pipeline.transform(X_train)
X_test_transformed = pipeline.transform(X_test)
print(X_train_transformed)
print(X_test_transformed)

[[ 0.50329748 -0.68139754 -0.51339594  0.06339599 -0.02091296]
 [-3.06497839  0.10762112 -0.65460507 -0.38454085  0.61279827]
 [ 7.81333268  4.87534865  0.68019349 -1.33761055 -0.36879346]
 ...
 [-0.40676779 -0.53874609 -0.83812814 -0.14665472  0.25293863]
 [-2.52014203 -0.14009838 -1.13270389  0.11733717 -0.21579831]
 [-3.0602268   0.33567098 -0.03572638 -0.3247422   0.43642598]]
[[-2.0157523  -0.23141196 -1.01740382  0.12647224 -0.20092461]
 [ 1.66819195 -0.56731743  0.69174235  0.11224257 -0.14804675]
 [ 2.05626846 -0.35431885  0.75062108  0.49022361 -0.27135771]
 ...
 [ 1.15400655  0.15551309  2.39755215  0.47445283 -0.93342324]
 [-1.68125369  0.74403879  1.63880625  0.3433723  -0.38065334]
 [ 0.72460704 -0.00640016  1.64948     0.27600769 -0.56427148]]


In [52]:
pipeline.fit(X_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('pca',
                                                                   PCA(n_components=5))]),
                                                  Index(['A', 'B', 'c', 'D', 'E'], dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index([], dtype='object'))]))])

In [54]:
X_train_transformed = pipeline.transform(X_train)
X_test_transformed = pipeline.transform(X_test)
print(X_train_transformed)
print(X_test_transformed)

[[ 0.50329748 -0.68139754 -0.51339594  0.06339599 -0.02091296]
 [-3.06497839  0.10762112 -0.65460507 -0.38454085  0.61279827]
 [ 7.81333268  4.87534865  0.68019349 -1.33761055 -0.36879346]
 ...
 [-0.40676779 -0.53874609 -0.83812814 -0.14665472  0.25293863]
 [-2.52014203 -0.14009838 -1.13270389  0.11733717 -0.21579831]
 [-3.0602268   0.33567098 -0.03572638 -0.3247422   0.43642598]]
[[-2.0157523  -0.23141196 -1.01740382  0.12647224 -0.20092461]
 [ 1.66819195 -0.56731743  0.69174235  0.11224257 -0.14804675]
 [ 2.05626846 -0.35431885  0.75062108  0.49022361 -0.27135771]
 ...
 [ 1.15400655  0.15551309  2.39755215  0.47445283 -0.93342324]
 [-1.68125369  0.74403879  1.63880625  0.3433723  -0.38065334]
 [ 0.72460704 -0.00640016  1.64948     0.27600769 -0.56427148]]
